// flow-typed signature: 846a601f5ebf1e3b62b3da5d0f4a1f33
// flow-typed version: <<STUB>>/reflexbox_v^4.0.6/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflexbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflexbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflexbox/dist/index' {
  declare module.exports: any;
}

declare module 'reflexbox/src/index' {
  declare module.exports: any;
}

declare module 'reflexbox/styled-components/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflexbox/dist/index.js' {
  declare module.exports: $Exports<'reflexbox/dist/index'>;
}
declare module 'reflexbox/src/index.js' {
  declare module.exports: $Exports<'reflexbox/src/index'>;
}
declare module 'reflexbox/styled-components/index.js' {
  declare module.exports: $Exports<'reflexbox/styled-components/index'>;
}
